#!/bin/bash

# Load the correct module
source ./test/load-module
ml list 

# Create a new virtual environment
python -m venv env/
source env/bin/activate 

# Install the correct MPI4PY 
env/bin/pip install --no-binary=mpi4py mpi4py

# Install the rest of depencies 
env/bin/pip install -r requirements_nek.txt

# Install the HydroGym package
env/bin/pip install -e . 
