# Dockerfile for a fully enabled Firedrake as base environment for HydroGym
#   Based on:
#   https://github.com/firedrakeproject/firedrake/blob/master/docker/Dockerfile.vanilla
#   https://github.com/firedrakeproject/firedrake/blob/master/docker/Dockerfile.firedrake

FROM lpaehler/hydrogym-firedrake-env:stable

USER firedrake
WORKDIR /home/firedrake

ENV PETSC_ARCH default

# Installation of basic Firedrake.
# RUN curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
# RUN bash -c "python3 firedrake-install \
#     --no-package-manager \
#     --disable-ssh \
#     --torch \
#     --honour-petsc-dir \
#     --mpicc=$MPICH_DIR/mpicc \
#     --mpicxx=$MPICH_DIR/mpicxx \
#     --mpif90=$MPICH_DIR/mpif90 \
#     --mpiexec=$MPICH_DIR/mpiexec"

# Installation of extra Firedrake components.
# RUN bash -c "source firedrake/bin/activate; \
#     firedrake-update \
#         --documentation-dependencies \
#         --netgen \
#         --slepc \
#         --tinyasm \
#         --install femlium \
#         --install fascd \
#         --install gusto \
#         --install irksome \
#         --install thetis"


# Installation of Nek-MARL dependencies.
# NOTE: This is a temporary solution to install the Nek-MARL package into the Firedrake environment.


RUN bash -c "git clone --recursive https://github.com/Fantasy98/hydrogym_NEK.git nek_hgym"

RUN bash -c "source firedrake/bin/activate; \  
    pip install -r requirements_nek.txt \
    pip install -e /home/nek_hgym"